/**
 * Copyright (c) 2025: Ahmed Samy, All rights reserved.
 * LinkedIn: https://www.linkedin.com/in/java-msdt/
 * GitHub: https://github.com/JAVA-MSDT
 * Email: serenitydiver@hotmail.com
 */
package com.javamsdt.masking.maskme.condition;

import com.javamsdt.masking.service.UserService;
import io.github.javamsdt.maskme.api.condition.MaskMeCondition;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

/**
 * Custom masking condition for Spring that masks phone numbers based on runtime input
 * and validation against a user database.
 * <p>
 * This condition demonstrates Spring's dependency injection with {@code @Component}
 * and Lombok's {@code @RequiredArgsConstructor} for automatic constructor generation.
 * </p>
 *
 * <p><b>Masking Logic:</b></p>
 * <ul>
 *   <li>Checks if the input matches the field value</li>
 *   <li>Validates if the phone number exists in the user database</li>
 *   <li>Only masks if both conditions are true</li>
 * </ul>
 *
 * <p><b>Usage Example:</b></p>
 * <pre>{@code
 * @MaskMe(conditions = {PhoneMaskingCondition.class}, maskValue = "****")
 * String phone;
 *
 * // In REST controller:
 * @GetMapping
 * public List<UserDto> getUsers(@RequestHeader("Mask-Phone") String maskPhone) {
 *     return users.stream()
 *         .map(user -> MaskMeInitializer.mask(userDto, PhoneMaskingCondition.class, maskPhone))
 *         .toList();
 * }
 * }</pre>
 *
 * <p><b>Spring Integration:</b></p>
 * <p>
 * The {@code @Component} annotation makes this a Spring-managed bean.
 * The {@code @RequiredArgsConstructor} (Lombok) generates a constructor
 * that Spring uses to inject the UserService dependency.
 * </p>
 *
 * @author Ahmed Samy
 * @since 1.0.0
 */
@Component
@RequiredArgsConstructor
public class PhoneMaskingCondition implements MaskMeCondition {

    /**
     * User service for validating phone numbers against the database.
     * Injected by Spring via constructor (generated by Lombok).
     */
    private final UserService userService;

    /**
     * Runtime input value to compare against the field value.
     * Set via {@link #setInput(Object)} method by MaskMe library.
     */
    private String input;

    /**
     * Determines whether the field should be masked based on:
     * <ol>
     *   <li>Input matches the field value</li>
     *   <li>Phone number exists in the user database</li>
     * </ol>
     *
     * @param maskedFieldValue            the current value of the field being evaluated
     * @param objectContainingMaskedField the object containing the field
     * @return true if the field should be masked, false otherwise
     */
    @Override
    public boolean shouldMask(Object maskedFieldValue, Object objectContainingMaskedField) {

        boolean anyUserPhoneMatched = userService.findUsers().stream()
                .anyMatch(user -> user.getPhone().equals(maskedFieldValue));

        // It will return true for only specific phone number, the rest in the collections will not be masked.
        return input != null
                && input.equals(maskedFieldValue)
                && anyUserPhoneMatched;
    }

    /**
     * Sets the runtime input value for this condition.
     * <p>
     * This method is called by the MaskMe library before evaluating the condition.
     * The input is typically provided via HTTP headers in REST controllers.
     * </p>
     *
     * @param input the input value (expected to be a String phone number)
     */
    @Override
    public void setInput(Object input) {
        if (input instanceof String) {
            this.input = (String) input;
        }
    }
}
